aliases = [
  "Int8Array",
  "Uint8Array",
  "Uint8ClampedArray",
  "Int16Array",
  "Uint16Array",
  "Int32Array",
  "Uint32Array",
  "Float32Array",
  "Float64Array",
  "DataView",
  "ArrayBuffer"
]
license = "MIT"
repo = "https://github.com/inexorabletash/polyfill"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray"

[browsers]
android = "<47"
bb = "*"
chrome = "<47"
edge = "<14"
edge_mob = "<14"
firefox = "<55"
firefox_mob = "<55"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "<10"
op_mini = "*"
op_mob = "<36"
opera = "<36"
safari = "<10"
samsung_mob = "<6"

[install]
module = "js-polyfills"
paths = [ "typedarray.js" ]

